### ISSUE TITLE
Calling `packr build/install` with a `*.go` files causes boxes not to be packed

### ISSUE THREAD

**Issue by selfup** [gobuffalo/packr#75] opened 2018-07-29 17:29 UTC
Hey so this is a longshot..

I am using `packr` to compile static assets to a single go binary.

It's a webserver. I can move the exe around on my machine and it works.

However when someone else on a different windows machine tries it, it says 404 not found :thinking_face:

Haven't tried on Mac yet, but I guess I would run into the same issues :joy:

Here is my repo: https://github.com/selfup/hmrcmd

Any help would be awesome! 🙏

**Comment by selfup** [comment] 2018-07-30 04:19
Ok so turns out you can't _really_ use any flag you want with `packr build`. If I do something like:

`packr build -o ./releases/foo main.go`

Then the files are not found. However:

`packr build && mv directory_name ./releases/foo`

Works!

Unclear if the language in the README needs to be updated or not, but this took me for quite the spin :joy: 

***

Here is an example I use:

```bash
npm run build \
  && mkdir releases \
  && GOOS=darwin GOARCH=amd64 packr build && mv ./hmrcmd ./releases/darwin-hmrcmd \
  && GOOS=linux GOARCH=amd64 packr build && mv ./hmrcmd ./releases/linux-hmrcmd \
  && GOOS=linux GOARCH=arm GOARM=5 packr build && mv ./hmrcmd ./releases/rpi-hmrcmd \
  && GOOS=windows GOARCH=386 packr build && mv ./hmrcmd.exe ./releases/hmrcmd.exe \
  && packr clean
```

Seems to do the trick

**Comment by alexsasharegan** [comment] 2018-07-30 05:41
I think I'm running into a similar problem trying to package something for a raspberry pi. Your mv fix isn't working for me.

**Comment by alexsasharegan** [comment] 2018-07-30 13:54
Yeah, and just to be clear, I didn't mean to imply the other lib is better or anything. I just needed something working by tomorrow, so after an hour debugging I was open to seeing if anything else "just worked".

**Comment by markbates** [comment] 2018-08-08 12:43
@selfup please make sure you are using the latest version. Also, when I tried to build it wouldn't because you were asking for `packr.NewBox("build")` which doesn't exist in the repo, causing it to fail. When I changed to it to `./src` it compiled correctly.

If the issue persists with the latest version of packr, please re-open. Thanks.

**Comment by selfup** [comment] 2018-08-08 18:29
@markbates `build` exist once you `npm run build`, there is a script in my `scripts` directory. Sorry for the confusion. I don't version control transpiled JS

**Comment by selfup** [comment] 2018-08-20 21:33
@marhaupe glad it saved you time 😄 

While not a fix, at least it's documented and indexed for those running into this as well.

Thanks for the re-open 🙏

**Comment by marhaupe** [comment] 2018-08-21 19:27
If anyone needs some test data: The snippet above can be found at https://github.com/marhaupe/GoReactBootstrap/blob/master/Dockerfile. packr version number at the time this didn't work was v1.13.2.

**Comment by markbates** [comment] 2018-09-12 23:41
I've updated the ticket title, since the cause of this issue is now known.

The problem is actually that when calling `go build main.go` Go only compiles `main.go` and any imports associated. So when running `packr build main.go` Go still only compiles `main.go` and ignores the the `*-packr.go` file in the directory.

The solution, until a "fix" can be found, is to call `packr build` with folders, not with files.

**Comment by selfup** [comment] 2018-09-13 22:54
Thanks for the update!

**Comment by markbates** [comment] 2018-09-21 14:17
I believe this PR solves this issue https://github.com/gobuffalo/packr/pull/94/files I would love those affected by this issue could try it out.

**Comment by marhaupe** [comment] 2018-09-21 21:33
I compiled the binary in your "small-fixes" branch with ```RUN CGO_ENABLED=0 GOOS=linux go build``` and directly copied it into the Docker-Container at https://github.com/marhaupe/go-react-bootstrap. Running 
```
RUN CGO_ENABLED=0 GOOS=linux ./packr build -a -installsuffix cgo -o /src/bin/GoReactBootstrap main.go
```

still won't produce the desired result. But to be completely honest, I'm not exactly sure if I compiled the binary correctly. Feel free to use the repo to reproduce the issue or give me a heads up on what I did wrong.

**Comment by selfup** [comment] 2018-09-21 23:02
I don't mind using `mv main ./releases`

If that's how it's going to be we should add a section to the README or something?

Thanks for the updates @marhaupe 🙏

**Comment by markbates** [comment] 2018-09-22 12:45
@marhaupe thanks for trying. Question, did you compile the binary under the v2 folder or the root folder? I just want to make sure you tried with v2, and not just v1. I’ll try your repo and see if I can figure it out. 

@selfup adding a note to the README about how Go works in those situations is a great. PR?

**Comment by selfup** [comment] 2018-09-22 15:41
Yea I can make one in a bit! Errands and stuff this morning. 👍

**Comment by marhaupe** [comment] 2018-09-22 15:50
@markbates I only compiled it for v1. Compiling it for v2 outputs the following error messages, but that is most likely due to a mistake on my side:
```
cannot find package "github.com/gobuffalo/packr/v2"
cannot find package "github.com/gobuffalo/packr/v2/file/resolver"
```
To compile the binary, I ran ```GO111MODULE=on go get && GOOS=linux go build``` from the ./v2/packr folder. Am I missing something?

**Comment by markbates** [comment] 2018-09-22 15:54
Go modules are screwing you up. You have to turn them off because it’s an unreleased branch and go modules can’t resolve it.

There’s a make install command in the v2 for compiling it.

But you’re app can’t use go modules while you’re testing any package that isn’t officially released yet. They haven’t done a good job with that part of the dev flow at all yet.

I can tell you I tried to build your repo using the v2 binary and it worked with the latest commit of that branch.

**Comment by selfup** [comment] 2018-09-22 16:27
PR is up https://github.com/gobuffalo/packr/pull/95 🎉

**Comment by markbates** [comment] 2018-11-16 21:12
This should be fixed in v2. Closing this issue for now. Please re-open if the problem still persists with v2.

**Closed by markbates** 2018-11-16 21:12 UTC
