### ISSUE TITLE
packr2 import issues with go modules

### ISSUE THREAD

**Issue by chmorgan** [gobuffalo/packr#183] opened 2019-03-30 15:55 UTC
Hello and thank you for a great tool!

I've been converting my projects over to go modules and ran into an issue with a project that uses packr2.

The issue is that the main-packr.go file imports by path:

```
...
import _ "Users/cmorgan/projects/xxxx/packrd
...
```

If I rewrite this to use the module path from the first line of go.mod:

```
module github.com/user/package/subdirectory
```

like:

```
...
import _ "github.com/user/package/subdirectory/packrd"
...
```

Everything works as expected.

It looks like you can retrieve this module like:

```
$ go list
github.com/user/package/subdirectory
```

Thoughts on how best to support go modules with packr2? I'm ok with rewriting the main-packrd.go file but I'm guessing lots of people are going to start bumping into this issue once they switch to go modules (which btw have worked pretty well, I was skeptical at first).

**Comment by markbates** [comment] 2019-03-30 16:33
I use packr exclusively with modules. We test on multiple platforms with modules.

Others have reported this issue, but no one has provided either a working example that demonstrates the problem, or a fix.

PRs are welcome.

-----------
Mark Bates

**Comment by chmorgan** [comment] 2019-03-30 17:04
@markbates are you checking in the generated packr files or setting GOPATH? I'm on go 1.12.1 here. I'd be curious what your main-packr.go files contain for a reference as a local path shouldn't work.

**Comment by markbates** [comment] 2019-03-30 17:07
// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr clean" command to clean up this,
// and any other packr generated files.
package main

import _ "tmp/packrd”

It works just fine. Do you have modules turned out? GO111MODULE=on If you don’t enable modules they won’t work.

-----------
Mark Bates

**Comment by chmorgan** [comment] 2019-03-30 17:14
@markbates modules are enabled if you are working outside of GOPATH or you are explicitly setting GO111MODULE=on. In my case I'm using the former. Or perhaps your project isn't itself a module?

The go devs indicate that these relative paths aren't supported but if yours is an absolute path I'm not sure that is also the case. https://github.com/golang/go/issues/26645#issuecomment-408572701

**Comment by chmorgan** [comment] 2019-03-30 17:21
@markbates let me create a simple example that reproduces the problem so we can discuss.

**Comment by markbates** [comment] 2019-03-30 17:22
Yes, no one else has. I can’t reproduce it, and use it more environments and situations than you might know.

This will have to be fixed by the community, since in all my experience, I haven’t run into this problem at all.

-----------
Mark Bates

**Comment by markbates** [comment] 2019-03-30 17:26
And to clarify it looks for a go.mod in the current directory and pulls the name of the module from that. If not, it falls back to trying to figure out your path. If you using go1.12 it will look for the GOMODS env first to find the go.mod file.

Make sure you’re using the latest version.

-----------
Mark Bates

**Comment by chmorgan** [comment] 2019-03-30 17:30
@markbates I'm using 2.0.9:

```
$ ~/go/bin/packr2 version
v2.0.9
```

and have a go.mod in my directory:

```
$ ls -l
total 20
-rw------- 1 cmorgan staff  102 Mar 30 13:25 go.mod
-rw------- 1 cmorgan staff 5664 Mar 30 13:25 go.sum
-rw-r--r-- 1 cmorgan staff  261 Mar 30 13:29 main-packr.go
-rw-r--r-- 1 cmorgan staff  163 Mar 30 13:29 main.go
drwxr-xr-x 3 cmorgan staff   96 Mar 30 13:29 packrd
drwxr-xr-x 3 cmorgan staff   96 Mar 30 13:28 templates
```

and seeing the wrong import in main-packr.go:

```
$ cat main-packr.go 
// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr clean" command to clean up this,
// and any other packr generated files.
package main

import _ "Users/cmorgan/projects/packrmodulesexample/packrd"
```

**Comment by chmorgan** [comment] 2019-03-30 17:33
@markbates https://github.com/chmorgan/packrmodulesexample

```
git clone https://github.com/chmorgan/packrmodulesexample
go get -u github.com/gobuffalo/packr/v2/packr2
cd packrmodulesexample
~/go/bin/packr2
go build
```

**Comment by chmorgan** [comment] 2019-03-30 17:33
```
$ go build
build github.com/chmorgan/packrmodulesexample: cannot load Users/cmorgan/projects/packrmodulesexample/packrd: cannot find module providing package Users/cmorgan/projects/packrmodulesexample/packrd
```

**Comment by markbates** [comment] 2019-03-30 17:36
Builds completely fine for me. Again, I am never able to reproduce this situation, so a fix is going to have to come from the community.

```
DEBU[2019-03-30T13:35:45-04:00] *parser.Parser#NewFromRoots options="{\"IgnoreImports\":false,\"Ignores\":null}" roots="[\"/Users/markbates/packrmodulesexample\"]"
DEBU[2019-03-30T13:35:45-04:00] *parser.Parser#NewFromRoots walking=/Users/markbates/packrmodulesexample
DEBU[2019-03-30T13:35:45-04:00] *parser.finder#findAllGoFilesImports dir=/Users/markbates/packrmodulesexample
DEBU[2019-03-30T13:35:45-04:00] *parser.finder#findAllGoFiles dir=/Users/markbates/packrmodulesexample
DEBU[2019-03-30T13:35:45-04:00] parser#IsProspect (TRUE) path=/users/markbates/packrmodulesexample/main.go status=true
DEBU[2019-03-30T13:35:45-04:00] *parser.Parser#NewFromRoots mapping=/Users/markbates/packrmodulesexample/main.go
DEBU[2019-03-30T13:35:45-04:00] parser#IsProspect (TRUE) path=/users/markbates/packrmodulesexample/main.go status=true
DEBU[2019-03-30T13:35:45-04:00] *parser.Parser#NewFromRoots mapping=/Users/markbates/packrmodulesexample/main.go
DEBU[2019-03-30T13:35:45-04:00] *parser.Parser#NewFromRoots reading file=/Users/markbates/packrmodulesexample/main.go
DEBU[2019-03-30T13:35:45-04:00] *parser.Parser#NewFromRoots found prospects=1
DEBU[2019-03-30T13:35:45-04:00] *parser.Parser#Run parsing=/Users/markbates/packrmodulesexample/main.go
DEBU[2019-03-30T13:35:45-04:00] *parser.Parser#Run box=embedded file=/Users/markbates/packrmodulesexample/main.go
DEBU[2019-03-30T13:35:45-04:00] *store.Disk#Clean box=embedded root=/Users/markbates/packrmodulesexample
DEBU[2019-03-30T13:35:45-04:00] *parser.Parser#NewFromRoots options="{\"IgnoreImports\":false,\"Ignores\":null}" roots="[\"/Users/markbates/packrmodulesexample\"]"
DEBU[2019-03-30T13:35:45-04:00] *parser.Parser#NewFromRoots walking=/Users/markbates/packrmodulesexample
DEBU[2019-03-30T13:35:45-04:00] *parser.finder#findAllGoFilesImports dir=/Users/markbates/packrmodulesexample
DEBU[2019-03-30T13:35:45-04:00] *parser.finder#findAllGoFiles dir=/Users/markbates/packrmodulesexample
DEBU[2019-03-30T13:35:45-04:00] parser#IsProspect (TRUE) path=/users/markbates/packrmodulesexample/main.go status=true
DEBU[2019-03-30T13:35:45-04:00] *parser.Parser#NewFromRoots mapping=/Users/markbates/packrmodulesexample/main.go
DEBU[2019-03-30T13:35:45-04:00] parser#IsProspect (TRUE) path=/users/markbates/packrmodulesexample/main.go status=true
DEBU[2019-03-30T13:35:45-04:00] *parser.Parser#NewFromRoots mapping=/Users/markbates/packrmodulesexample/main.go
DEBU[2019-03-30T13:35:45-04:00] *parser.Parser#NewFromRoots reading file=/Users/markbates/packrmodulesexample/main.go
DEBU[2019-03-30T13:35:45-04:00] *parser.Parser#NewFromRoots found prospects=1
DEBU[2019-03-30T13:35:45-04:00] *parser.Parser#Run parsing=/Users/markbates/packrmodulesexample/main.go
DEBU[2019-03-30T13:35:45-04:00] *parser.Parser#Run box=embedded file=/Users/markbates/packrmodulesexample/main.go
DEBU[2019-03-30T13:35:45-04:00] *store.Disk#Clean box=embedded root=/Users/markbates/packrmodulesexample
DEBU[2019-03-30T13:35:45-04:00] *parser.Parser#NewFromRoots options="{\"IgnoreImports\":false,\"Ignores\":null}" roots="[\"/Users/markbates/packrmodulesexample\"]"
DEBU[2019-03-30T13:35:45-04:00] *parser.Parser#NewFromRoots walking=/Users/markbates/packrmodulesexample
DEBU[2019-03-30T13:35:45-04:00] *parser.finder#findAllGoFilesImports dir=/Users/markbates/packrmodulesexample
DEBU[2019-03-30T13:35:45-04:00] *parser.finder#findAllGoFiles dir=/Users/markbates/packrmodulesexample
DEBU[2019-03-30T13:35:45-04:00] parser#IsProspect (TRUE) path=/users/markbates/packrmodulesexample/main.go status=true
DEBU[2019-03-30T13:35:45-04:00] *parser.Parser#NewFromRoots mapping=/Users/markbates/packrmodulesexample/main.go
DEBU[2019-03-30T13:35:45-04:00] parser#IsProspect (TRUE) path=/users/markbates/packrmodulesexample/main.go status=true
DEBU[2019-03-30T13:35:45-04:00] *parser.Parser#NewFromRoots mapping=/Users/markbates/packrmodulesexample/main.go
DEBU[2019-03-30T13:35:45-04:00] *parser.Parser#NewFromRoots reading file=/Users/markbates/packrmodulesexample/main.go
DEBU[2019-03-30T13:35:45-04:00] *parser.Parser#NewFromRoots found prospects=1
DEBU[2019-03-30T13:35:45-04:00] *parser.Parser#Run parsing=/Users/markbates/packrmodulesexample/main.go
DEBU[2019-03-30T13:35:45-04:00] *parser.Parser#Run box=embedded file=/Users/markbates/packrmodulesexample/main.go
DEBU[2019-03-30T13:35:45-04:00] found 1 boxes
DEBU[2019-03-30T13:35:45-04:00] *store.Disk#Pack box=embedded
DEBU[2019-03-30T13:35:45-04:00] *store.Disk#Close
DEBU[2019-03-30T13:35:45-04:00] Step: f6102e7f
DEBU[2019-03-30T13:35:45-04:00] Chdir: /Users/markbates/packrmodulesexample
DEBU[2019-03-30T13:35:45-04:00] File: /Users/markbates/packrmodulesexample/packrd/packed-packr.go
DEBU[2019-03-30T13:35:45-04:00] File: /Users/markbates/packrmodulesexample/main-packr.go
```

```
// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr clean" command to clean up this,
// and any other packr generated files.
package main

import _ "github.com/chmorgan/packrmodulesexample/packrd"
```

**Comment by markbates** [comment] 2019-03-30 17:51
If it helps https://github.com/gobuffalo/packr/blob/master/v2/jam/store/disk.go that’s where the import is calculated.

**Comment by chmorgan** [comment] 2019-03-30 17:54
@markbates thanks. I did find that, looking now. Btw 'modsOn' isn't used in the code anywhere from what I can see:

https://github.com/gobuffalo/packr/search?q=modsOn&unscoped_q=modsOn

I'll dig in. This shouldn't be too hard to fix. What I'm not sure about is how it works for you. Are you also using go 1.12.1? I'm on macOS here.

**Comment by markbates** [comment] 2019-03-30 17:56
Mac 1.12 as well as windows. And we have a testing matrix of 15 combinations on Mac, Linux, and windows. 1.10-1.12 modules on/off.

-----------
Mark Bates

**Comment by chmorgan** [comment] 2019-03-30 18:28
@markbates alright, I think I found it. There are a couple of issues:

- In disk.go 

```

        var ip string
        if envy.Mods() {
                // Starting in 1.12, we can rely on Go's method for
```

either envy.Mods() has to be improved to check for either GO111MODULES=on OR if GOPATH is not set, or that if should be modified to be if envy.Mods() || envy.Get("GOPATH", "") == "" {

I'm not sure when the behavior changed, maybe in 1.12 but if you aren't inside of the GOPATH directory or if GOPATH isn't set, then module support is enabled.

- In envy the environment is being manipulated at https://github.com/gobuffalo/envy/blob/master/envy.go#L61 which prevents the suggested modification to v2/jam/store/disk.go


If I set GO111MODULE=on my main-packr.go file is generated correctly, but since modules support is assumed if outside of GOPATH or if GOPATH isn't set, the check in packr isn't entirely correct at the moment. https://github.com/golang/go/wiki/Modules#how-to-install-and-activate-module-support

I can submit PRs for the issues if you can provide some direction on the approach you'd like to see. I'd probably be inclined to modify envy.Mods() to include the check, and drop the GOPATH environment variable override in another commit earlier in that series. Imo envy shouldn't be modifying the path for the user but the code that does so doesn't indicate why this was necessary or desired.

**Comment by markbates** [comment] 2019-03-30 18:33
We don't support `auto` mode. https://gobuffalo.io/en/docs/gomods

**Comment by markbates** [comment] 2019-03-30 18:34
I'm fine turning it on if you're outside your GOPATH, but we won't support `auto` inside the GOPATH.

**Comment by chmorgan** [comment] 2019-03-30 18:37
@markbates how about if we perform the mods check during init and set a flag for use by the Mods() function? Then we can override the GOPATH variable with GO ENV GOPATH (which I presume was done to be helpful to the end user in case GOPATH wasn't set?)

You mean GO111MODULE=auto? I'm not sure anyone is really using that at the moment. I'd at least be happy if the unset GOPATH and unset GO111MODULE == modules enabled (as go cmd treats it)

**Comment by chmorgan** [comment] 2019-03-30 18:39
@markbates oh but I guess you are correct, the user could set GOPATH and operate outside of it.

That seems to simplify the check in envy.Mods() then, look for GO111MODULE=on or if CWD is outside of GOPATH (not sure how to do that path check but it should be possible)

**Comment by markbates** [comment] 2019-03-30 18:43
I guess I'm not really sure what you mean, I don't see how one impacts the other, tbh. we set GOPATH for those that don't have it set because a lot of tooling still looks for it, so it's trying to be helpful.

`if envy.Mods() || envy.Get("GOPATH", "") == "" {` doesn't make sense if you're in GOPATH, without modules, and don't have GOPATH set, then it's going to assume modules? That's not correct behavior either.

"but since modules support is assumed if outside of GOPATH" that's `GO111MODULE=auto`, which isn't supported by Packr.

Perhaps you should make a PR and then we can discuss, because I don't see how those things fit together. 

If I'm outside the GOPATH and turns modules on `GO111MODULE=on` everything works just fine. If I don't do that, it fails, as expected.

I could just be missing something.

**Comment by markbates** [comment] 2019-03-30 18:43
`envy.InGoPath()`

**Comment by chmorgan** [comment] 2019-03-30 18:44
@markbates from the go docs module support is enabled if you set GO111MODULE=on or if you are outside of GOPATH. I'm lazy and using that behavior rather than explicitly setting GO111MODULE=on.

Let me push a PR against envy, its a one liner fix thanks to your comment. One min.

**Comment by markbates** [comment] 2019-03-30 18:51
You’re talking about `GO111MODULE=auto` mode. We don’t support that. You have to turn on modules `GO111MODULE=on`.

I know the rules around modules, and we made a conscious decision to NOT support `auto` and require people to turn them on explicitly.

-----------
Mark Bates

**Comment by chmorgan** [comment] 2019-03-30 18:58
@markbates auto is mentioned as a distinct setting for GO111MODULE in the go docs, I was misunderstanding what you meant as go also autodetects module support with 1.11 (or was it 1.12?)

Anything I can do to convince you that we should modify envy.Mods() like:

```
// Mods returns true if module support is enabled, false otherwise
// See https://github.com/golang/go/wiki/Modules#how-to-install-and-activate-module-support for details on how
// go determines if module support is enabled or not
//
// Note: GO111MODULE=auto is not supported
func Mods() bool {
        return (Get(GO111MODULE, "off") == "on" || !InGoPath())
}
```

I'm not sure I can see why we wouldn't want to support what people are going to typically do for modules support now that go 1.12 has taken modules out of testing.

**Comment by markbates** [comment] 2019-03-30 19:06
It is a distinct setting, but it's also the default setting. In 1.13 it will default to `on`. 

You can open a PR and we can talk about it, but `auto` was one of the worst decisions they made with Modules.

**Comment by chmorgan** [comment] 2019-03-30 19:13
@markbates ok. I'be pushed out a PR against envy. I'm just thinking I can't be the only one to expect the behavior here to match what go does. I can see that it could be confusing but I haven't been bitten by any modules issues thus far with the auto detection approach they are using.

**Comment by cdreier** [comment] 2019-04-22 20:51
hi, i just ran in the same issue when building with the `-mod vendor` flag

seems like `packr2 build` works diffrent than `packr2 build -v` ?

when running `GO111MODULE=on packr2 build -mod vendor` i get the same error as shown above

```
can't load package: package drailing.net/debugging/vendor: no Go files in /home/dreiling/gows/src/drailing.net/debugging/vendor
Error: exit status 1
```

`GO111MODULE=on go build -mod vendor` in the same setup/directory is working fine

i found 2 ways to get this working for me

1. just running `packr2` generating the packr files and then running `go build` - manually cleaning up the packr files

2. adding the verbose flag, seems like to fix it in a similar way. the file are generated and the go command runs successfully, but no automatic cleanup is done

if you need more informations or if i can help in any way, feed free to ping me

**Comment by chmorgan** [comment] 2019-04-22 23:17
@cdreier what version of packr2 are you running? You'll want to confirm it is 2.2.0 as that contains the envy fix for module detection (although you are forcing it to on). I'm not sure this is the same issue although I'm also not using the -mod vendor option either.

**Comment by cdreier** [comment] 2019-04-23 06:31
@chmorgan i can confirm, after running in problems i updated everything (packr2 is v2.2.0), but that did not help

i created a small repository where you can reproduce the behaviour

https://github.com/cdreier/packr2-mod-vendor

**Comment by cdreier** [comment] 2019-04-25 06:49
@markbates is this related to this issue? perhaps this behaviour is more with the vendor folder, indirectly with go modules. should i open a new issue?

**Comment by markbates** [comment] 2019-04-25 11:20
I don’t know. I don’t use vendor. I use modules exclusively and haven’t hit this issue, but I couldn’t say for sure.

**Closed** 2019-05-21 12:26 UTC
